### ISSUE TITLE
RNOAA troubles

### ISSUE THREAD

**Issue by icaruso21** [icaruso21/Insect-Phenology-Forecaster#1]
On line 12 I am importing a the local copy of ghcnd-stations.csv and then referencing it here in an attempt to create a new dataframe containing the nearest weather station for every entry using the RNOAA library. For some reason it is giving me an error... "replacement has 0 rows, data has 1493", any ideas? 

https://github.com/icaruso21/Insect-Phenology-Forecaster/blob/8595e816417f9ce7a594170e4ec78e7bf84b6c80/app.R#L33-L44

**Comment by ys634** [comment]
Made changes. Check if it works now.

**Comment by icaruso21** [comment]
I'm still getting a curl error with this new implementation below. Not quite sure why that is. 

https://github.com/icaruso21/Insect-Phenology-Forecaster/blob/60ef046aa5446988a75d4a330e95be8ddd8233cb/app.R#L76-L91
