### ISSUE TITLE
Subscript out of bounds for some cumulative dd calculations? 

### ISSUE THREAD

**Issue by icaruso21** [icaruso21/Insect-Phenology-Forecaster#3]
After implementing the cumulative degree day column to calculate total degree days, this error started showing up for a few stations. 
![Screen Shot 2020-05-25 at 9 24 37 PM](https://user-images.githubusercontent.com/44649197/82860495-b2e49d80-9ece-11ea-975d-53495ff5dde8.png)

**Comment by icaruso21** [comment]
Some code for context about where I made the change: 
https://github.com/icaruso21/Insect-Phenology-Forecaster/blob/ba4a4a92c7d65bfd474a40e82ad96e40a3721236/app.R#L167-L180

**Comment by lbuckley** [comment]
The error generally means that you are indexing a matrix etc. at a position larger than the data structure. Perhaps the indexing is occurring within one of the functions?
