### ISSUE TITLE
Should we use PMAP for 'expensive' computations? 

### ISSUE THREAD

**Issue by icaruso21** [icaruso21/Insect-Phenology-Forecaster#7]
PMAP is a relatively simple way to parallelize code across multiple processors. Essentially, instead of applying the function passed into MAP sequentially (as done by the traditional map function), multithreading is used by PMAP to apply the desired function simultaneously to multiple indexes in the list. When doing expensive computations (updating rasters for example), we could potentially see a large speedup from using this technique vs the traditional map function. Will the EC2 instance used for deployment will have multiple cores? This is really a question of cost, not practicality, as EC2 makes it simple to create an instance with an arbitrary number of cores. 

https://purrr.tidyverse.org/reference/map2.html

**Comment by lbuckley** [comment]
PMAP seems good to look into. AWS structure is flexible.
