### ISSUE TITLE
'zipcode' library is outdated

### ISSUE THREAD

**Issue by icaruso21** [icaruso21/Insect-Phenology-Forecaster#8]
Evidently, the zipcode library is not supported by R version 4.0. Is there an alternative library for getting latitude and longitude of a zipcode without simply downloading a dataset of zipcodes and their corresponding lat/lon values? I have not been able to find any suitable alternatives so far.

**Comment by lbuckley** [comment]
I don't know of any. Could use a map click or allow lat / lon entry?
